ventory:
    plugin: SimpleInventory
    options:
        host_file: "C:/Users/MaYiCk-GiO-DC/Desktop/U3.2-Python-Nornir-Nexus9K/hosts.yaml"
        group_file: "C:/Users/MaYiCk-GiO-DC/Desktop/U3.2-Python-Nornir-Nexus9K/groups.yaml"
nner:
plugin: threaded
options:
    num_workers: 20